### ISSUE TITLE
Migration of WSRR Policies?

### ISSUE THREAD

**Issue by malarchezhian** [ibm-apiconnect/soa-transfer-tool#6]
What's the recommended way of migrating **WSRR Policies** to API Connect?  Looks like the SOAT tool does not retrieve Policy details.

- Data Grid Caching Policy
- Policy Set Domain
- SOAP Message Transmission Optimization Mechanism - Serialization Policy
- Service Level Mediation Policy
- Service Level Monitoring Policy
- Situation Policy
- WAS JMS Transport Policy Domain
- WAS Security Policy 1.2 Extensions
- WAS Transport Policy Domain
- WS Addressing WSDL Policy Domain
- WSRR Service Metadata Governance Policy 6.2
- Web Services Atomic Transaction 1.0 Policy
- Web Services Atomic Transaction 1.1 Policy
- Web Services Business Activity Framework 1.0 Policy
- Web Services Business Activity Framework 1.1 Policy
- Web Services Reliable Messaging Policy 1.0
- Web Services Reliable Messaging Policy 1.1
- Web Services Security Policy 1.1
- Web Services Security Policy 1.2

Can any of these WSRR policies be imported directly as custom policy in APIC? (or) mapped to any built-in policy in the Assembly?  Please advise.

**Comment by abutch3r** [comment]
As the recent editions of IBM Datapower are still compliant with the WS-Policy 1.2 and 1.5 standards then the basis for those policies should allow for them to be imported into APIC as user-defined policies within API Connect. 

The way policies have been built within WSRR mean that they are not suitable candidates for retrieval via the Transfer tool, while metadata about a created policy could be captured the actual content behind it cannot be extracted in a suitable way with the transfer tool. Links to the policy in the Assembly section would definitely be possible to be programatically included as part of the template depending on the required policy.

It should be noted that the last update on any of the WSRR policies was in 2012, and Datapower has added a lot of functionality in between 2012 and 2018 that may be better at achieving some of the original goals of these policies or in the recent versions have been update. WSRR 8.5 supports WS-Mediation upto 1.7, 7.7 of datapower goes from 1.6 to 1.9 .

If you would like to try and get these policies as part of the API connect product you would need to raise an RFE against API Connect to look at migrated these policies.
